/* 独立测试画布：操作真实页面，媒体与运行状态为本地夹具，不提交模型。 */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
(async()=>{
 const base=process.env.CANVAS_TEST_URL||'http://127.0.0.1:3001';const output=path.resolve('cache/maintenance');fs.mkdirSync(output,{recursive:true});process.env.TMPDIR=output;process.env.TMP=output;process.env.TEMP=output;
 const api=async(p,body,method)=>{const r=await fetch(base+p,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d;};
 const made=await api('/api/canvases',{title:'节点呈现验收_临时',kind:'smart'});const cid=made.id||made.canvas?.id;
 const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{channel:'chrome'}),headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const url=route.request().url();if(!url.startsWith(base)&&!url.startsWith('data:'))return route.abort();if(route.request().method()==='POST'&&/\/api\/canvas-(?:image-tasks|video|audio|music|llm)/.test(url))throw Error('验收禁止模型请求');return route.continue();});
 try{
 await page.goto(`${base}/static/smart-canvas.html?id=${cid}`);await page.waitForFunction(()=>typeof canvas!=='undefined'&&canvas&&typeof CanvasNodeView!=='undefined');
 const id=await page.evaluate(()=>{const n=createNode(140,150,[{kind:'text',name:'分段剧本.md',text:'# 城门交剑\n林澈慢慢交出旧剑。\n\n'+('守门人抬头。\n'.repeat(25))}],{select:false});n.title='E01_S01_P01_交剑';n.w=620;n.h=350;CanvasCreation.ensure(n);n.resultVersions=Array.from({length:25},(_,i)=>({id:'version_'+i,images:[{kind:'text',name:'原文.md',text:'版本 '+(i+1)+'\n林澈慢慢交出旧剑。'}],title:'旧名称_'+i,createdAt:Date.now()+i}));n.activeResultVersion=0;viewport.scale=1;viewport.x=0;viewport.y=0;selectedId=n.id;selectedIds=[];render();return n.id;});
 let node=page.locator(`.image-node[data-id="${id}"]`);
 assert.equal(await node.locator('.node-delete').count(),1);assert.equal(await node.locator('.image-delete,.floating-node-actions').count(),0);
 const header=await node.locator('.node-head').boundingBox(),del=await node.locator('.node-delete').boundingBox();assert.ok(del.y+del.height<header.y);
 const railInfo=async()=>page.evaluate(id=>{const n=document.querySelector(`.image-node[data-id="${id}"]`),r=n.getBoundingClientRect(),bs=[...n.querySelectorAll('[data-result-version]')].map(b=>b.getBoundingClientRect());return {right:r.right,firstX:bs[0].x,rows:bs.filter(b=>Math.abs(b.x-bs[0].x)<1).length,columns:new Set(bs.map(b=>Math.round(b.x))).size};},id);
 const before=await railInfo();assert.ok(before.firstX>before.right);assert.ok(before.columns>=2);
 const rail=node.locator('.result-version-switcher');assert.ok(await rail.isVisible());
 const style=await rail.evaluate(el=>{const active=el.querySelector('button.active'),other=el.querySelector('button:not(.active)');return {radius:getComputedStyle(el).borderRadius,active:getComputedStyle(active).backgroundColor,other:getComputedStyle(other).backgroundColor};});assert.notEqual(style.active,style.other);assert.equal(style.radius,'12px');
 await page.evaluate(()=>{clearSelection();render();});assert.equal(await rail.isVisible(),false);await node.hover();assert.equal(await rail.isVisible(),false);
 await node.locator('.node-body').click({position:{x:10,y:15}});assert.ok(await rail.isVisible());

 await node.locator('[data-creation-title]').dblclick();let input=node.locator('[data-node-title-input]');await input.fill('E01_S01_P01_主动交剑');await input.press('Enter');assert.equal(await node.locator('[data-creation-title]').textContent(),'E01_S01_P01_主动交剑');
 await node.locator('[data-result-version="1"]').click();assert.equal(await node.locator('[data-creation-title]').textContent(),'E01_S01_P01_主动交剑');
 await node.locator('[data-creation-title]').dblclick();await input.fill('取消的名字');await input.press('Escape');assert.equal(await node.locator('[data-creation-title]').textContent(),'E01_S01_P01_主动交剑');
 await node.locator('[data-creation-title]').dblclick();await input.fill('重绘中的草稿');await input.evaluate(el=>{el.selectionStart=el.selectionEnd=3;});await page.evaluate(()=>render());assert.equal(await input.inputValue(),'重绘中的草稿');assert.equal(await input.evaluate(el=>el.selectionStart),3);await input.press('Escape');
 const grip=await node.locator('.node-resize-handle').boundingBox();await page.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2);await page.mouse.down();await page.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2+150,{steps:8});await page.mouse.up();
 const after=await railInfo();assert.ok(after.rows>before.rows,JSON.stringify({before,after}));assert.ok(after.firstX>after.right);
 assert.equal(await node.locator('details.node-tools-menu').count(),0);assert.ok(await node.locator('[data-smart-node-action="template"]').isVisible());
 await page.evaluate(()=>StudioTheme.apply('dark'));await page.waitForTimeout(400);await page.screenshot({path:path.join(output,'node-presentation-text.png')});
 const imageId=await page.evaluate(()=>{const n=createExecutionNode(140,150,'smart-image-generator',{select:false});n.title='林澈_妆造_正常';n.w=620;n.h=350;n.images=[{kind:'image',url:'/static/images/logo.png',name:'林澈.png'}];nodes=nodes.filter(x=>x.id===n.id);selectedId='';selectedIds=[];const task=CanvasCreation.begin(nodes,n);task.runStatus='running';task.pending=1;render();return n.id;});
 node=page.locator(`.image-node[data-id="${imageId}"]`);assert.equal(await node.locator('.creation-running-glass').count(),1);assert.equal(await node.locator('[data-cancel-run]').count(),1);assert.ok(!(await node.locator('.creation-tasks').textContent()).includes('%'));
 // 动效实例和任务时间连续：真实点选、拖动画布、滚轮缩放、重绘、改尺寸均不得重启。
 await page.evaluate(id=>{const el=document.querySelector(`.image-node[data-id="${id}"] .creation-running-glass`);window.runningLayer=el;window.runningAnimation=el.querySelector('.creation-running-mover').getAnimations()[0];},imageId);
 await page.waitForTimeout(300);
 const initialTime=await page.evaluate(()=>runningAnimation.currentTime);
 await node.locator('.node-body').click({position:{x:10,y:80}});
 await page.mouse.move(1050,850);await page.mouse.down();await page.mouse.move(1150,890,{steps:8});await page.mouse.up();
 await page.mouse.wheel(0,180);await page.waitForTimeout(350);
 const continuity=await page.evaluate(id=>{const n=nodes.find(n=>n.id===id);n.w+=30;for(let i=0;i<8;i++)render();const el=document.querySelector(`.image-node[data-id="${id}"] .creation-running-glass`);return {sameLayer:el===runningLayer,sameAnimation:el.querySelector('.creation-running-mover').getAnimations()[0]===runningAnimation,time:runningAnimation.currentTime,state:runningAnimation.playState};},imageId);
 assert.ok(continuity.sameLayer&&continuity.sameAnimation);assert.ok(continuity.time>initialTime+300);assert.equal(continuity.state,'running');
 await page.evaluate(id=>{nodes.find(n=>n.id===id).w=620;viewport={x:0,y:0,scale:1};applyViewport();clearSelection();render();},imageId);
 await page.screenshot({path:path.join(output,'node-presentation-running.png')});
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>runningAnimation.playState==='paused');
 const pausedTime=await page.evaluate(()=>runningAnimation.currentTime);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>runningAnimation.currentTime),pausedTime);
 await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>runningAnimation.playState==='running');
 await node.locator('[data-cancel-run]').click();await page.waitForFunction(id=>!document.querySelector(`.image-node[data-id="${id}"] .creation-running-glass`),imageId);assert.equal(await node.locator('.node-img').count(),1);assert.equal(await page.evaluate(()=>runningAnimation.playState),'idle');
 await node.locator('.node-body').click({position:{x:10,y:15}});await page.waitForTimeout(300);const position=await page.evaluate(id=>{const n=document.querySelector(`.image-node[data-id="${id}"]`).getBoundingClientRect(),c=document.querySelector('#composer').getBoundingClientRect();return {bottom:n.bottom,top:c.top,nodeWidth:n.width,composerWidth:c.width,open:document.querySelector('#composer').classList.contains('open')};},imageId);assert.ok(position.open&&position.top>=position.bottom,JSON.stringify(position));assert.ok(Math.abs(position.nodeWidth-position.composerWidth)<3,JSON.stringify(position));
 await page.screenshot({path:path.join(output,'node-presentation-composer.png')});

 // 同一标题栏骨架覆盖所有运行类型与素材类型，空结果运行也能取消。
 const fixtureIds=await page.evaluate(()=>{nodes=[];selectedId='';selectedIds=[];const kinds=['smart-text-generator','smart-image-generator','smart-video-generator','smart-audio-generator','smart-music-generator','smart-ai-app'];const result=kinds.map(type=>{const n=createExecutionNode(140,150,type,{select:false});n.title=type;n.w=620;n.h=350;return n.id;});viewport.scale=.6;render();return result;});
 for(const nodeId of fixtureIds){const el=page.locator(`.image-node[data-id="${nodeId}"]`);assert.equal(await el.locator('.node-head .node-delete').count(),1);assert.equal(await el.locator('.node-body .node-delete,.image-delete').count(),0);}
 const blankId=fixtureIds[1];await page.evaluate(id=>{nodes=nodes.filter(n=>n.id===id);const n=nodes[0];const t=CanvasCreation.begin(nodes,n);t.runStatus='running';render();},blankId);const blank=page.locator(`.image-node[data-id="${blankId}"]`);assert.equal(await blank.locator('.creation-running-glass').count(),1);
 await page.evaluate(()=>{viewport={x:0,y:0,scale:1};applyViewport();render();});
 // 不同任务具有不同随机轨迹，长时间运行也能继续；明暗主题和窄窗口不改变动画。
 const tracks=await page.evaluate(()=>{const a=document.querySelector('.creation-running-mover').getAnimations()[0];window.blankAnimation=a;const first=a.effect.getKeyframes().map(f=>f.transform);const n=createExecutionNode(860,150,'smart-video-generator',{select:false});n.w=400;n.h=240;const t=CanvasCreation.begin(nodes,n);t.runStatus='running';render();const b=document.querySelectorAll('.creation-running-glass')[1].querySelector('.creation-running-mover').getAnimations()[0];return {first,second:b.effect.getKeyframes().map(f=>f.transform)};});assert.notDeepEqual(tracks.first,tracks.second);
 for(const theme of ['dark','light']){await page.evaluate(theme=>StudioTheme.apply(theme),theme);await page.waitForTimeout(200);await page.screenshot({path:path.join(output,'running-empty-'+theme+'.png')});}
 await page.setViewportSize({width:700,height:850});await page.waitForTimeout(150);assert.ok(await blank.locator('[data-cancel-run]').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));await page.screenshot({path:path.join(output,'running-empty-narrow.png')});await page.setViewportSize({width:1440,height:1100});
 await page.evaluate(()=>{blankAnimation.currentTime=180000;render();});assert.ok(await page.evaluate(()=>blankAnimation.currentTime>=180000));await page.evaluate(()=>StudioTheme.apply('dark'));
 await blank.locator('[data-cancel-run]').click();assert.equal(await page.evaluate(()=>blankAnimation.playState),'idle');assert.equal(await blank.locator('.creation-running-glass').count(),0);
 await page.emulateMedia({reducedMotion:'reduce'});
 for(const kind of ['text','image','video','audio']){const mid=await page.evaluate(kind=>{nodes=[];const item=kind==='text'?{kind,text:'完整正文',name:'说明.md'}:{kind,url:'/static/images/logo.png',name:'素材.'+({image:'png',video:'mp4',audio:'wav'}[kind])};const n=createNode(140,150,[item],{select:false});n.title='验收_'+kind;n.w=620;n.h=350;render();return n.id;},kind);const el=page.locator(`.image-node[data-id="${mid}"]`);assert.equal(await el.locator('.node-head .node-delete').count(),1);assert.equal(await el.locator('.node-head [data-smart-node-action="preview"]').count(),1);assert.equal(await el.locator('.node-body [data-smart-node-action],.image-delete').count(),0);}
 await page.evaluate(async()=>{nodes[0].title='保存后保留_音频';await saveCanvas();});await page.reload();await page.waitForFunction(()=>typeof canvas!=='undefined'&&canvas&&nodes.some(n=>n.title==='保存后保留_音频'));const saved=page.locator('.image-node').filter({has:page.locator('[data-creation-title]',{hasText:'保存后保留_音频'})});await saved.locator('.node-body').click({position:{x:10,y:15}});await saved.locator('.node-delete').click();await page.waitForFunction(()=>!nodes.some(n=>n.title==='保存后保留_音频'));
 // 参数一级入口在长模型名、明暗主题及窄屏下保持同高，并提供完整名称。
 await page.setViewportSize({width:1440,height:1100});
 await page.evaluate(()=>{nodes=[];const n=createExecutionNode(400,140,'smart-image-generator',{select:false});selectedId=n.id;selectedIds=[];viewport={x:0,y:0,scale:1};render();applyViewport();});
 const setupControls=()=>page.evaluate(()=>{dynamicParams.innerHTML=renderExecutionConfigPanel(renderExecutionChoiceControl('平台','plug-zap','provider-control','',false,false,'laohu')+renderExecutionChoiceControl('模型','image','model-control','<button>laohu Image G V2 · 低价版</button>',false,false,'laohu Image G V2 · 低价版')+renderExecutionChoiceControl('运行模式','list-filter','model-variant-control','',false,false,'低价渠道版'),null);refreshIcons();});
 for(const theme of ['light','dark']){await page.evaluate(t=>StudioTheme.apply(t),theme);await setupControls();await page.waitForTimeout(350);const boxes=await page.locator('#dynamicParams .execution-choice-pill').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {y:r.y,h:r.height,w:r.width,white:getComputedStyle(el.querySelector('.execution-control-label')).whiteSpace,title:el.title};}));assert.equal(boxes.length,3);assert.ok(boxes.every(b=>b.y===boxes[0].y&&b.h===boxes[0].h&&b.white==='nowrap'));assert.ok(boxes[1].w>boxes[0].w);assert.ok(boxes[1].title.includes('laohu Image G V2 · 低价版'));await page.screenshot({path:path.join(output,'parameter-row-'+theme+'.png')});}
 await page.setViewportSize({width:480,height:1000});await setupControls();const narrow=await page.locator('#dynamicParams .execution-choice-pill').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,h:r.height,w:r.width};}));assert.ok(narrow[1].y>narrow[0].y&&narrow[2].y>narrow[1].y);assert.ok(narrow.every(b=>Math.abs(b.h-narrow[0].h)<.1),JSON.stringify(narrow));await page.setViewportSize({width:1440,height:1100});
 // 参数有限范围完整点选；默认整行、画幅等高、选项命中无遮挡。
 const choices=await page.evaluate(()=>({short:capabilityParameterChoiceOptions('duration',{type:'integer',min:4,max:15}),long:capabilityParameterChoiceOptions('duration',{type:'integer',min:4,max:30}),official:capabilityParameterChoiceOptions('duration',{type:'enum',options:[5,10]}),res:capabilityParameterChoiceOptions('resolution',{type:'enum',options:['1.5k','2k','4k']})}));assert.deepEqual(choices.short,Array.from({length:12},(_,i)=>i+4));assert.deepEqual(choices.long,Array.from({length:27},(_,i)=>i+4));assert.deepEqual(choices.official,[5,10]);assert.deepEqual(choices.res,['1.5k','2k','4k']);
 for(const key of ['duration','aspect_ratio','resolution']){
  await page.evaluate(key=>{const spec=key==='duration'?{type:'integer',min:4,max:30,level:'optional'}:{type:'enum',level:'optional',...(key==='resolution'?{options:['1.5k','2k','4k']}:{})};const profile={provider_id:'test',model_id:'test',parameters:{[key]:spec}};const ed=renderCapabilityParameterEditor(key,spec,profile,{});dynamicParams.innerHTML=renderCapabilityParameterControl(key,ed.label,spec,profile,ed.value,ed.unset,ed.body,ed.extraClass);bindDynamicParams();const control=dynamicParams.querySelector('.smart-control');control.classList.add('pinned');positionPinnedSmartPopover(control);refreshIcons();},key);
  const grid=page.locator('#dynamicParams .capability-option-grid'),unset=grid.locator('[data-capability-unset]');assert.equal(await unset.textContent(),'默认');assert.equal(await unset.locator('[data-capability-option-drag-handle]').count(),0);assert.equal(await page.locator('#dynamicParams input').count(),0);const g=await grid.boundingBox(),d=await unset.boundingBox();assert.ok(d.width>g.width*.85);const option=grid.locator('[data-capability-option]').first();assert.ok(await option.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));await page.screenshot({path:path.join(output,'parameter-options-'+key+'.png')});
 }
 // 无连线的四种媒体都能真实拖拽交换，正文引用与实际输入一致。
 for(const kind of ['image','text','video','audio']){
  await page.evaluate(kind=>{nodes=[];canvas.connections=[];const n=createExecutionNode(400,140,'smart-image-generator',{select:false});const refs=[0,1].map(i=>({kind,name:kind+i,...(kind==='text'?{text:'正文'+i}:{url:'/static/images/logo.png?'+kind+i})}));n.manualInputRefs=refs;n.promptDraftHtml=refs.map(mentionTokenHtml).join(' 然后 ');selectedId=n.id;selectedIds=[];viewport={x:0,y:0,scale:1};render();},kind);
  const thumbs=page.locator('#inputThumbsRow .input-thumb');assert.equal(await thumbs.count(),2);assert.equal(await thumbs.nth(0).getAttribute('draggable'),'true');await page.mouse.move(30,900);await page.evaluate(()=>hideReferenceHoverPreview());await thumbs.nth(0).dragTo(thumbs.nth(1));
  const state=await page.evaluate(()=>{const n=selectedNode(),refs=defaultReferenceImagesFor(n);return {keys:refs.map(inputRefKey),html:n.promptDraftHtml,edges:canvas.connections,request:buildPromptRequestForNode(n,refs).refs};});assert.ok(state.keys[0].endsWith('1'),JSON.stringify({kind,...state}));assert.equal(state.edges.length,0);assert.ok(state.html.includes(kind==='text'?'data-text="正文1"':kind+'1'));if(kind!=='text')assert.ok(state.request[0].url.endsWith(kind+'1'));
 }
 // 混合有线/无线路径，以及 Shift 全局交换的消费者同步。
 await page.evaluate(()=>{nodes=[];canvas.connections=[];const source=createNode(100,100,[{kind:'image',url:'/static/images/logo.png?source',name:'源'}],{select:false});const a=createExecutionNode(400,140,'smart-image-generator',{select:false});const b=createExecutionNode(1200,140,'smart-image-generator',{select:false});a.manualInputRefs=[{kind:'image',url:'/static/images/logo.png?manual',name:'手动'}];b.manualInputRefs=structuredClone(a.manualInputRefs);connectInputNode(source.id,a.id);selectedId=a.id;selectedIds=[];viewport={x:0,y:0,scale:1};render();});
 await page.locator('#inputThumbsRow .input-thumb').nth(0).dragTo(page.locator('#inputThumbsRow .input-thumb').nth(1));assert.ok(await page.evaluate(()=>defaultReferenceImagesFor(selectedNode())[0].url.endsWith('manual')));
 await page.mouse.move(30,900);await page.waitForTimeout(500);await page.evaluate(()=>hideReferenceHoverPreview());await page.keyboard.down('Shift');await page.locator('#inputThumbsRow .input-thumb').nth(0).dragTo(page.locator('#inputThumbsRow .input-thumb').nth(1));await page.keyboard.up('Shift');assert.ok(await page.evaluate(()=>nodes.find(n=>n.x===1200).manualInputRefs[0].url.endsWith('source')));assert.equal(await page.evaluate(()=>canvas.connections.length),1);
 // 文本生成的真实请求也读取无连线输入的交换顺序。
 await page.evaluate(()=>{nodes=[];canvas.connections=[];const n=createExecutionNode(400,140,'smart-text-generator',{select:false});n.promptDraftText='总结';n.manualInputRefs=[{kind:'text',text:'甲'},{kind:'text',text:'乙'}];selectedId=n.id;selectedIds=[];render();});await page.locator('#inputThumbsRow .input-thumb').nth(0).dragTo(page.locator('#inputThumbsRow .input-thumb').nth(1));assert.deepEqual(await page.evaluate(()=>textGenerationMediaForNode(selectedNode()).texts),['乙','甲']);
 const swapSaved=await page.evaluate(async()=>{await saveCanvas();return {id:selectedNode().id,order:selectedNode().inputRefOrder};});await page.reload();await page.waitForFunction(id=>typeof canvas!=='undefined'&&canvas&&nodes.some(n=>n.id===id),swapSaved.id);assert.deepEqual(await page.evaluate(id=>textGenerationMediaForNode(nodes.find(n=>n.id===id)).texts,swapSaved.id),['乙','甲']);
 assert.deepEqual(errors,[]);console.log('通过：唯一头部删除、版本右侧分列和真实拖拽重排、原位改名/取消/重绘光标、展开工具栏、任务动效跨点选/拖动/缩放/重绘连续、取消清理/减少动效、输入位于下方、参数行长名称/明暗/窄屏对齐、范围选项/默认整行、四类无连线引用交换/实际请求/保存重开、混合引用和Shift全局交换。');
 }finally{await browser.close();await api(`/api/canvases/${cid}/purge`,null,'DELETE');}
})().catch(e=>{console.error(e);process.exitCode=1});
