/* 无付费的真实手势回归：虚线归属、底部抽屉、独立缩放工具。使用自己的临时画布。 */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const base=process.env.CANVAS_TEST_URL||'http://127.0.0.1:3001',out=path.resolve('cache/maintenance');process.env.TMPDIR=out;process.env.TEMP=out;process.env.TMP=out;
const api=async(p,body,method)=>{const r=await fetch(base+p,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.json();};const made=await api('/api/canvases',{title:'虚线抽屉验收_临时',kind:'smart'}),cid=made.id||made.canvas.id;
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>{const q=r.request();if(!q.url().startsWith(base)&&!q.url().startsWith('data:'))return r.abort();if(q.method()==='POST'&&/\/api\/canvas-(image|video|audio|music|llm)/.test(q.url()))return r.abort();return r.continue();});
try{await page.goto(`${base}/static/smart-canvas.html?id=${cid}`);await page.waitForFunction(()=>typeof canvas!=='undefined'&&canvas&&apiProviders.length);
const ids=await page.evaluate(()=>{nodes=[];canvas.connections=[];viewport={x:0,y:0,scale:1};const s=createNode(120,170,[{kind:'text',text:'林澈走进院落。',name:'第1段.md'}],{select:false}),a=createExecutionNode(620,170,'smart-image-generator',{select:false}),v=createExecutionNode(1100,170,'smart-video-generator',{select:false});for(const n of [s,a,v]){n.w=260;n.h=180;}s.title='第1段_进入院落';a.title='林澈_妆造';v.title='第1段_视频';CanvasProduction.update(s,{role:'segment',order:1},nodes);selectedId='';selectedIds=[];render();applyViewport();return {s:s.id,a:a.id,v:v.id};});
const drag=async(from,to,button)=>{const a=await page.locator(`.image-node[data-id="${from}"] > .node-body`).boundingBox(),b=await page.locator(`.image-node[data-id="${to}"] > .node-body`).boundingBox();await page.keyboard.down('Shift');await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down({button});await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:12});await page.mouse.up({button});await page.keyboard.up('Shift');};
await drag(ids.s,ids.a,'right');await page.waitForTimeout(250);
let state=await page.evaluate(ids=>({edges:canvas.connections,refs:inputNodesFor(nodes.find(n=>n.id===ids.a)).map(n=>n.id),rows:CanvasProduction.rows(nodes,canvas.connections),editing:!!document.querySelector('.media-text-editor')}),ids);
assert.ok(state.edges.some(c=>c.from===ids.s&&c.to===ids.a&&c.kind==='story'));assert.deepEqual(state.refs,[]);assert.equal(state.rows[0].images[0].id,ids.a);assert.equal(state.editing,false);assert.equal(await page.locator('.conn-line.conn-story').count(),1);
await drag(ids.a,ids.v,'left');assert.ok(await page.evaluate(ids=>canvas.connections.some(c=>c.from===ids.a&&c.to===ids.v&&c.kind==='input'),ids));
await page.evaluate(ids=>{connectInputNode(ids.s,ids.a);const i=canvas.connections.findIndex(c=>c.from===ids.s&&c.to===ids.a&&c.kind==='story');disconnectConnection(i);},ids);assert.deepEqual(await page.evaluate(ids=>inputNodesFor(nodes.find(n=>n.id===ids.a)).map(n=>n.id),ids),[ids.s]);assert.equal(await page.evaluate(()=>CanvasProduction.rows(nodes,canvas.connections)[0].images.length),0);
// 原接口批量登记转换为同一种虚线，并验证保存后读取。
await page.evaluate(async ids=>{CanvasProduction.update(nodes.find(n=>n.id===ids.s),{imageNodeIds:[ids.a],videoNodeIds:[ids.v]},nodes,canvas.connections);render();await saveCanvas();},ids);await page.reload();await page.waitForFunction(()=>typeof canvas!=='undefined'&&canvas&&nodes.some(n=>n.production?.role==='segment'));assert.equal(await page.locator('.production-chip').count(),2);
const panel=page.locator('.canvas-production-panel'),grip=panel.locator('[data-pin]');
await page.evaluate(()=>StudioTheme.apply('dark'));await page.waitForTimeout(250);
const beforeGrip=await grip.boundingBox(),beforePanel=await panel.boundingBox();
assert.equal(await grip.getAttribute('aria-pressed'),'true');assert.ok(beforeGrip.y>=beforePanel.y);assert.ok(Math.abs(beforeGrip.x+beforeGrip.width/2-beforePanel.x-beforePanel.width/2)<1);
assert.ok(await grip.evaluate(el=>{const s=getComputedStyle(el);return s.borderTopWidth==='0px'&&s.backgroundColor==='rgba(0, 0, 0, 0)'&&s.boxShadow==='none';}));
assert.equal(await grip.locator('.production-grip-ring').isVisible(),true);await panel.screenshot({path:path.join(out,'drawer-pinned-dark.png')});
await grip.click();await page.waitForTimeout(250);assert.equal(await grip.getAttribute('aria-pressed'),'false');assert.equal(await grip.locator('.production-grip-lines').isVisible(),true);
const released=await grip.boundingBox();assert.ok(Math.abs(released.x-beforeGrip.x)<1&&Math.abs(released.y-beforeGrip.y)<1);await panel.screenshot({path:path.join(out,'drawer-unpinned-dark.png')});
await page.evaluate(()=>StudioTheme.apply('light'));await panel.screenshot({path:path.join(out,'drawer-unpinned-light.png')});
await page.mouse.move(400,90);await page.waitForTimeout(400);let r=await panel.boundingBox();assert.ok(r.y>1060,JSON.stringify(r));await page.mouse.move(720,1092);await page.waitForTimeout(350);assert.ok((await panel.boundingBox()).y<1060);await grip.click();await page.mouse.move(400,90);await page.waitForTimeout(350);assert.equal(await panel.evaluate(el=>el.classList.contains('is-auto-hide')),false);
await panel.locator('[data-close]').click();
await page.evaluate(ids=>{const n=nodes.find(n=>n.id===ids.a);n.images=[{kind:'image',url:'/static/images/logo.png',name:'林澈.png',natural_w:512,natural_h:512}];selectedId=n.id;selectedIds=[n.id];viewport={x:0,y:0,scale:1};render();applyViewport();},ids);
const geometry=async()=>page.evaluate(id=>{const n=document.querySelector(`.image-node[data-id="${id}"]`),head=n.querySelector('.node-head').getBoundingClientRect(),body=n.querySelector('.node-body').getBoundingClientRect(),button=n.querySelector('.node-delete').getBoundingClientRect(),c=composer.getBoundingClientRect();return {headH:head.height,headBottom:head.bottom,bodyTop:body.top,bodyW:body.width,buttonW:button.width,composerW:c.width,composerTop:c.top,bodyBottom:body.bottom};},ids.a);
const large=await geometry();await page.evaluate(()=>{viewport.scale=.25;viewport.x=320;viewport.y=130;applyViewport();});await page.waitForTimeout(300);const small=await geometry();console.log({large,small});assert.ok(Math.abs(large.buttonW-small.buttonW)<1);assert.ok(Math.abs(large.composerW-small.composerW)<1);assert.ok(small.bodyW<large.bodyW*.3);assert.ok(small.headBottom<small.bodyTop);assert.ok(small.composerTop>small.bodyBottom);
await page.evaluate(()=>StudioTheme.apply('dark'));await page.waitForTimeout(450);await page.screenshot({path:path.join(out,'relations-floating-quarter.png')});const toolbar=page.locator(`.image-node[data-id="${ids.a}"] [role="toolbar"]`);assert.equal(await toolbar.locator('details,summary').count(),0);for(const key of ['preview','crop','outpaint','mask','brush','grid','download']){const action=toolbar.locator(`[data-smart-node-action="${key}"]`);assert.ok(await action.isVisible());assert.ok(await action.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));}assert.equal(await page.locator(`.image-node[data-id="${ids.s}"] [role="toolbar"]`).isVisible(),false);await page.evaluate(()=>{clearSelection();render();});assert.equal(await toolbar.isVisible(),false);assert.equal(await page.locator('#composer').evaluate(el=>el.classList.contains('open')),false);
await page.evaluate(()=>StudioI18n.set('en'));assert.equal(await page.locator('[data-i18n="smart.shortcutStoryConnection"]').textContent(),'Create a dashed relation, without model input');// 整理只就近对齐选中项，尺寸/引用保持，撤销及保存后结果一致。
const grid=await page.evaluate(()=>{nodes=[];canvas.connections=[];viewport={x:100,y:100,scale:.65};const make=(x,y,w,h,name)=>{const n=createNode(x,y,[{kind:'text',text:name,name:name+'.md'}],{select:false});n.w=w;n.h=h;n.manualResized=true;n.title=name;return n;};const a=make(61,51,316,194,'小节点'),b=make(845,77,632,388,'四格节点'),fixed=make(3300,100,316,194,'未选中');canvas.connections=[{from:a.id,to:fixed.id,kind:'story'}];selectedId=a.id;selectedIds=[];render();applyViewport();return {a:a.id,b:b.id,fixed:fixed.id,before:nodes.map(n=>({id:n.id,x:n.x,y:n.y,w:n.w,h:n.h})),edges:JSON.stringify(canvas.connections)};});
const snapshot=()=>page.evaluate(()=>nodes.map(n=>({id:n.id,x:n.x,y:n.y,w:n.w,h:n.h})));
await page.locator('#smartArrangeBtn').click();let single=await snapshot();assert.deepEqual(single.find(n=>n.id===grid.fixed),grid.before.find(n=>n.id===grid.fixed));assert.deepEqual(single.find(n=>n.id===grid.b),grid.before.find(n=>n.id===grid.b));assert.notDeepEqual(single.find(n=>n.id===grid.a),grid.before.find(n=>n.id===grid.a));
await page.keyboard.press('Meta+z');assert.deepEqual(await snapshot(),grid.before);
await page.evaluate(ids=>{selectedId=ids.a;selectedIds=[ids.a,ids.b];render();},grid);await page.locator('#smartArrangeBtn').click();const aligned=await snapshot();assert.equal(await page.evaluate(()=>JSON.stringify(canvas.connections)),grid.edges);for(const n of aligned){const old=grid.before.find(x=>x.id===n.id);assert.equal(n.w,old.w);assert.equal(n.h,old.h);}
await page.evaluate(()=>{viewport.scale=.25;applyViewport();});await page.locator('#smartArrangeBtn').click();assert.deepEqual(await snapshot(),aligned);
await page.screenshot({path:path.join(out,'grid-alignment.png')});await page.evaluate(()=>saveCanvas());await page.reload();await page.waitForFunction(()=>typeof canvas!=='undefined'&&canvas&&nodes.length===3);assert.deepEqual(await snapshot(),aligned);assert.equal(await page.locator('#smartArrangeLabel').textContent(),'Align selected');
// 已有分组作为一个整体对齐，不改变成员相对位置。
const groupBefore=await page.evaluate(()=>{nodes=[];canvas.connections=[];const child=createNode(120,130,[{kind:'text',text:'组内',name:'组内.md'}],{select:false});const g=createSmartGroupNode(81,73,{select:false});g.items=[child.id];selectedId=g.id;selectedIds=[];render();return {group:g.id,child:child.id,dx:child.x-g.x,dy:child.y-g.y};});await page.locator('#smartArrangeBtn').click();const delta=await page.evaluate(ids=>{const g=nodes.find(n=>n.id===ids.group),c=nodes.find(n=>n.id===ids.child);return {dx:c.x-g.x,dy:c.y-g.y};},groupBefore);assert.deepEqual(delta,{dx:groupBefore.dx,dy:groupBefore.dy});
assert.deepEqual(errors,[]);console.log('通过：Shift右键虚线/左键实线、虚线不入模型、独立删除、表格保存同步、抽屉悬停与固定、25%缩放可点击尺寸、展开工具栏命中/未选中隐藏、中英文快捷键、就近宫格单选/多选/撤销/尺寸保留/缩放稳定/保存重开/分组平移。');
}finally{await browser.close();await api(`/api/canvases/${cid}/purge`,null,'DELETE');}})().catch(e=>{console.error(e);process.exitCode=1});
